-- AlterTable
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "building" TEXT NOT NULL DEFAULT 'Главный корпус';
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "floor" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "equipment" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Auditory" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Backfill code from name for existing rows
UPDATE "Auditory" SET "code" = "id" WHERE "code" IS NULL OR "code" = '';

ALTER TABLE "Auditory" ALTER COLUMN "code" SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "Auditory_code_key" ON "Auditory"("code");

ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
